#!/usr/bin/env bash
# Compare Cord source / compile output sizes vs hand-written JSX & Svelte.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMPARE="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

CORDLANG="$ROOT/cordlang"
[[ -x "$CORDLANG" ]] || CORDLANG="$ROOT/cordlang.exe"
if [[ ! -x "$CORDLANG" && ! -f "$CORDLANG" ]]; then
  echo "FAIL: build cordlang first"
  exit 1
fi

bytes() {
  wc -c < "$1" | tr -d ' '
}

OUT="$COMPARE/RESULTS.md"
{
  echo "# Compare results"
  echo ""
  echo "Generated by \`bench/compare/run_compare.sh\` on $(date -u +%Y-%m-%dT%H:%MZ)."
  echo ""
  echo "Sizes are **UTF-8 byte counts**. Compile output is \`cordlang compile --backend …\`."
  echo "Hand-written sources are idiomatic micro-equivalents, not line-for-line identical emit."
  echo ""
  echo "| Case | Cord src | Cord→React emit | Cord→Svelte emit | Hand JSX | Hand Svelte | Compile React (ms) |"
  echo "|------|----------|-----------------|------------------|----------|-------------|--------------------|"
} > "$OUT"

measure_compile_ms() {
  local file="$1" backend="$2"
  local t0 t1
  t0=$(date +%s%N)
  "$CORDLANG" compile "$file" --backend "$backend" >/dev/null
  t1=$(date +%s%N)
  echo $(( (t1 - t0) / 1000000 ))
}

for case_dir in "$COMPARE"/cases/*/; do
  [[ -d "$case_dir" ]] || continue
  name="$(basename "$case_dir")"
  cord="$case_dir/app.cord"
  [[ -f "$cord" ]] || continue

  cord_b=$(bytes "$cord")
  tmp_r=$(mktemp)
  tmp_s=$(mktemp)
  "$CORDLANG" compile "$cord" --backend react >"$tmp_r"
  "$CORDLANG" compile "$cord" --backend svelte >"$tmp_s"
  react_b=$(bytes "$tmp_r")
  svelte_b=$(bytes "$tmp_s")
  rm -f "$tmp_r" "$tmp_s"

  jsx=$(find "$case_dir" -maxdepth 1 -name '*.jsx' | head -n1)
  sv=$(find "$case_dir" -maxdepth 1 -name '*.svelte' | head -n1)
  jsx_b="—"
  sv_b="—"
  [[ -n "$jsx" && -f "$jsx" ]] && jsx_b=$(bytes "$jsx")
  [[ -n "$sv" && -f "$sv" ]] && sv_b=$(bytes "$sv")

  ms=$(measure_compile_ms "$cord" react)

  echo "| $name | $cord_b | $react_b | $svelte_b | $jsx_b | $sv_b | $ms |" >> "$OUT"
  echo "PASS: $name cord=$cord_b react_emit=$react_b svelte_emit=$svelte_b jsx=$jsx_b svelte=$sv_b compile_ms=$ms"
done

{
  echo ""
  echo "## Notes"
  echo ""
  echo "- Prefer comparing **Cord src** vs **Hand JSX/Svelte** for AI token density."
  echo "- Emit size is often larger than Cord src (expected); compare emit vs hand-written for codegen verbosity."
  echo "- Times are single-shot wall clock; use \`make bench\` for medians."
} >> "$OUT"

echo ""
echo "Wrote $OUT"
